apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
        envFrom:
        - secretRef:
            name: mysql-secret
        - configMapRef:
            name: mysql-config
        # env:
        # - name: MYSQL_ROOT_PASSWORD
        #   # value: Pl123456
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-secret
        #       key: root_password

        # - name: MYSQL_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       key: mysql_password
        #       name: mysql-secret
        # - name: MYSQL_USER
        #   value: clarus
        # - name: MYSQL_DATABASE
        #   value: phonebook
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-persistent-volume

      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: mysql-pv-claim